ifndef top_dir
problem:
	@echo "your Makefile must define top_dir before including Makefile.config"
	exit 1
endif

bin_dir=$(shell readlink -f $(top_dir)/bin)
inc_dir=$(shell readlink -f $(top_dir)/include)
fs_dir=$(shell readlink -f $(top_dir)/fs)
obj_dir=$(shell readlink -f $(cur_dir)/obj)
proj_dir=$(shell readlink -f $(top_dir))

DEF_CFLAGS=-I$(inc_dir) -Wall -pthread -lrt -ldl -lulockmgr -g
DEF_LDFLAGS=-I$(inc_dir) `pkg-config fuse --cflags --libs` `pkg-config libzbc --cflags --libs` 

LDFLAGS=$(DEF_LDFLAGS)
CFLAGS=$(DEF_CFLAGS)
CC=gcc
RM=$(shell which rm) -rf
CP=$(shell which cp) -f
MV=$(shell which mv) -f
MKDIR=$(shell which mkdir) -p
NAME=optsmr

dirs:
	@$(MKDIR) $(bin_dir)
	@$(MKDIR) $(obj_dir)

.DEFAULT_GOAL := all
